// engine/designspec.mjs — render the per-page design spec (references/page-design-spec.md format) as a
// ready-to-present Markdown artifact, DETERMINISTICALLY, from the Freedom ChangeSet.
//
// Why this exists: telling the agent (in prose) to "produce a per-page design spec populated from the
// ChangeSet" repeatedly produced a loose PARAPHRASE — fields dumped as prose, no per-field table, no
// container/colSpan, standard features re-labelled wrong ("Timeline", "Expanded list"). The agent cannot
// paraphrase a table it did not write. So the engine emits the table itself and the skill presents it
// verbatim. This is the "what goes where" the user approves at the gate.
//
// Input = the runMigration() result (entity, changeSet, effective, decisionSummary). Output = a Markdown
// string. It invents NOTHING the ChangeSet does not contain; unresolved items become ⚠ rows/decisions.

const strip = (s) => (s == null ? "" : String(s).replace(/^\$/, ""));
const esc = (s) => strip(s).replace(/\|/g, "\\|"); // keep table cells from breaking on a literal pipe
const isField = (o) => !!(o && o.values && o.values.control);

// Climb the emitted insert tree from a field's parentName to the region that holds it: a crt.Tab → that
// tab, SideAreaProfileContainer → the side profile, HeaderContainer → the header, else the raw container
// name (a base-template container not re-emitted here).
function regionResolver(viewConfigDiff) {
  const byName = new Map(viewConfigDiff.map((o) => [o.name, o]));
  const label = (o) => esc(o.values && o.values.caption ? strip(o.values.caption) : o.name);
  return (parentName) => {
    let p = parentName, hops = 0, first = null; // `first` = container directly holding the field (the island, #9b)
    while (p && hops++ < 64) {
      if (p === "SideAreaProfileContainer") return first ? `Side profile › ${first}` : "Side profile";
      if (p === "HeaderContainer") return "Header";
      if (p === "GeneralInfoTabContainer") return "⚠ fallback (unresolved)";
      const o = byName.get(p);
      if (!o) return esc(p);
      if (o.values && o.values.type === "crt.Tab") return `Tab "${label(o)}"`;
      if (!first) first = label(o); // remember the innermost container so profile islands read distinctly
      p = o.parentName;
    }
    return esc(parentName);
  };
}

const COMPONENT_LABEL = {
  "crt.Input": "Input", "crt.ComboBox": "Dropdown/Lookup", "crt.Checkbox": "Checkbox",
  "crt.DateTimePicker": "Date/Time", "crt.NumberInput": "Number",
};

export function renderDesignSpec(result, opts = {}) {
  const cs = result.changeSet || {};
  const eff = result.effective || {};
  const entity = result.entity || "?";
  const vcd = cs.viewConfigDiff || [];
  const regionOf = regionResolver(vcd);
  const fields = vcd.filter(isField);

  // rule lookup: element/column -> the page rule(s) that target it
  const ruleByEl = new Map();
  for (const r of cs.pageBusinessRules || []) {
    const line = `${r.action}${r.inverseAction ? ` (+${r.inverseAction})` : ""}`;
    ruleByEl.set(r.element, (ruleByEl.get(r.element) ? ruleByEl.get(r.element) + "; " : "") + line);
  }
  for (const r of cs.entityBusinessRules || []) {
    const line = `filter${r.complete ? "" : " ⚠"}`;
    ruleByEl.set(r.targetAttribute, (ruleByEl.get(r.targetAttribute) ? ruleByEl.get(r.targetAttribute) + "; " : "") + line);
  }

  const L = [];
  L.push(`## Design spec — ${entity} form page (generated from the ChangeSet)`);
  L.push("");
  L.push("> Auto-generated by `migrate.mjs` from the merged Classic layers. Every field's container,");
  L.push("> colSpan, component, attribute, plus the details, actions and rules below are the ENGINE's");
  L.push("> output — **present verbatim, do not paraphrase**. Items needing human judgment are marked ⚠");
  L.push("> and collected under *Decisions*.");
  L.push("");
  L.push(`- **Entity:** ${entity}`);
  if (opts.template) L.push(`- **Freedom template:** ${opts.template}`);
  if (opts.targetPackage) L.push(`- **Target package:** ${opts.targetPackage}`);
  L.push(`- **Counts:** ${fields.length} fields · ${(cs.details || []).length} custom details · ${(cs.standardFeatures || []).length} standard features · ${(cs.cardActions || []).length} card actions · ${(cs.pageBusinessRules || []).length} page rules · ${(cs.entityBusinessRules || []).length} entity rules`);
  if (eff.unresolvedParents && eff.unresolvedParents.length)
    L.push(`- ⚠ **unresolvedParents:** ${eff.unresolvedParents.join(", ")} — the seed is incomplete; DO NOT build until this is empty`);
  L.push("");

  // ---- Region map ----
  const regionOrder = [];
  const regionHolds = new Map();
  const addTo = (region, item) => {
    if (!regionHolds.has(region)) { regionHolds.set(region, []); regionOrder.push(region); }
    regionHolds.get(region).push(item);
  };
  for (const f of fields) addTo(regionOf(f.parentName), esc(strip(f.values.control)));
  for (const d of cs.details || []) addTo(d.tab ? tabRegion(d.tab, vcd) : "⚠ unplaced", `▤ ${esc(d.detailSchema || d.entity)} (list)`);
  for (const s of cs.standardFeatures || []) addTo(s.tab ? tabRegion(s.tab, vcd) : "⚠ unplaced", `★ ${esc(s.feature)}`);
  L.push("### Region map");
  L.push("| Region | Holds |");
  L.push("| --- | --- |");
  for (const r of regionOrder) L.push(`| ${r} | ${regionHolds.get(r).join(" · ")} |`);
  L.push("");

  // ---- Fields ----
  L.push("### Fields");
  L.push("| Classic column | Freedom component | Attribute | Container | Col · colSpan | Rule |");
  L.push("| --- | --- | --- | --- | --- | --- |");
  for (const f of fields) {
    const col = strip(f.values.control);
    const lc = f.values.layoutConfig || {};
    const comp = COMPONENT_LABEL[f.values.type] || f.values.type;
    const cell = `${lc.column ?? "?"} · ${lc.colSpan ?? "?"}`;
    const vis = f.values.visible === false ? " · hidden" : "";
    L.push(`| ${esc(col)} | ${esc(comp)}${vis} | PDS.${esc(col)} | ${esc(f.parentName)} | ${cell} | ${ruleByEl.get(col) || "—"} |`);
  }
  L.push("");

  // ---- Details & standard features ----
  if ((cs.details || []).length || (cs.standardFeatures || []).length) {
    L.push("### Details & standard features");
    L.push("| Classic detail | Freedom target | Tab | Note |");
    L.push("| --- | --- | --- | --- |");
    for (const s of cs.standardFeatures || [])
      L.push(`| ${esc(s.classicDetail || s.entity)} | ★ ${esc(s.feature)} — ${esc(s.freedom)} | ${esc(s.tab || "⚠ unplaced")} | ${s.templateProvided ? "template-provided — do NOT recreate" : ""}${s.inferredFromEntity ? " · inferred from entity, confirm" : ""} |`);
    for (const d of cs.details || []) {
      const note = [
        d.dependency ? `by ${esc(d.dependency.attributePath)}` : "⚠ FK unresolved",
        d.columns && d.columns.length ? `cols: ${d.columns.map(esc).join(", ")}` : null,
      ].filter(Boolean).join(" · ");
      L.push(`| ${esc(d.detailSchema || d.entity)} | ▤ Expanded list (${esc(d.entity)}) | ${esc(d.tab || "⚠ unplaced")} | ${note} |`);
    }
    L.push("");
  }

  // ---- Card actions ----
  if ((cs.cardActions || []).length) {
    L.push("### Card actions");
    L.push(cs.cardActions.map((a) => `\`${esc(a)}\``).join(" · "));
    L.push("");
  }

  // ---- Page rules ----
  if ((cs.pageBusinessRules || []).length || (cs.entityBusinessRules || []).length) {
    L.push("### Business rules");
    L.push("| Target | Kind | Action | Complete |");
    L.push("| --- | --- | --- | --- |");
    for (const r of cs.pageBusinessRules || [])
      L.push(`| ${esc(r.element)} | page | ${esc(r.action)} (+${esc(r.inverseAction)}) | yes |`);
    for (const r of cs.entityBusinessRules || [])
      L.push(`| ${esc(r.targetAttribute)} | entity | ${esc(r.action)} | ${r.complete ? "yes" : "⚠ resolve value"} |`);
    L.push("");
  }

  // ---- Decisions (the 20%) ----
  const nd = cs.needsDecision || [];
  if (nd.length) {
    L.push(`### Decisions — ⚠ needs human judgment (${nd.length})`);
    for (const d of nd) L.push(`- **[${esc(d.kind)}]** ${esc(d.item)} — ${strip(d.reason)}`);
    L.push("");
  }

  return L.join("\n");
}

// map a detail's `tab` (a container/tab NAME) to its region label using the emitted tree
function tabRegion(tab, viewConfigDiff) {
  return regionResolver(viewConfigDiff)(tab);
}
