// engine/designspec.mjs — render the per-page design spec (references/page-design-spec.md format) as a
// ready-to-present Markdown artifact, DETERMINISTICALLY, from the Freedom ChangeSet.
//
// Why this exists: telling the agent (in prose) to "produce a per-page design spec" repeatedly produced a
// loose PARAPHRASE — no per-field table, features mislabelled. The agent cannot paraphrase a table it did
// not write, so the engine emits it and the skill presents it verbatim.
//
// The spec is ONE layout table (structure + contents, no repetition) + a Logic table (behaviour that is
// not layout) + a Confirm list (the ⚠ worklist). Input = the runMigration() result. Output = Markdown.
// Markdown tables cannot merge cells, so the Region column REPEATS per row (grouped, first-seen order).

const strip = (s) => (s == null ? "" : String(s).replace(/^\$/, ""));
const esc = (s) => strip(s).replace(/\|/g, "\\|"); // keep table cells from breaking on a literal pipe
const isField = (o) => !!o?.values?.control;
const DASH = "—";

// Climb the emitted insert tree from a container to the region that holds it: crt.Tab → that tab,
// SideAreaProfileContainer → the side profile (with the island container appended, #9b), Header → header,
// else the raw container name (a base-template container not re-emitted here).
function regionResolver(viewConfigDiff) {
  const byName = new Map(viewConfigDiff.map((o) => [o.name, o]));
  const label = (o) => esc(o.values?.caption ? strip(o.values.caption) : o.name);
  return (parentName) => {
    let p = parentName, hops = 0, first = null;
    while (p && hops++ < 64) {
      if (p === "SideAreaProfileContainer") return first ? `Side profile › ${first}` : "Side profile";
      if (p === "HeaderContainer") return "Header";
      if (p === "GeneralInfoTabContainer") return "⚠ fallback (unresolved)";
      const o = byName.get(p);
      if (!o) return esc(p);
      if (o.values?.type === "crt.Tab") return `Tab · ${label(o)}`;
      if (!first) first = label(o);
      p = o.parentName;
    }
    return esc(parentName);
  };
}

// field display name = its resolved label (human title) when available, else the column code.
const dispLabel = (o) => { const l = o.values?.label; return (l && !String(l).startsWith("$")) ? String(l) : strip(o.values.control); };
const humanizeAction = (a) => ({ "make-required": "required", "make-optional": "optional", "make-read-only": "read-only", "make-editable": "editable", "show-element": "visible", "hide-element": "hidden" }[a] || a);
const triggerOf = (m) => {
  const mt = /^on(.+?)Chang/.exec(m);
  if (mt) return `${mt[1]} changes`;
  if (/init/i.test(m)) return "on load";
  if (/save/i.test(m)) return "on save";
  return "—";
};
// demote a nested design spec's Markdown headings two levels (## → ####, ### → #####, capped at ######)
// so a child page's spec reads as a subsection under the parent plan's `#### Child page:` heading.
const demoteHeadings = (md) => String(md).replace(/^(#{2,6}) /gm, (_m, h) => "#".repeat(Math.min(6, h.length + 2)) + " ");

export function renderDesignSpec(result, opts = {}) {
  const cs = result.changeSet || {};
  const eff = result.effective || {};
  const section = result.section || null;
  const entity = result.entity || "?";
  const vcd = cs.viewConfigDiff || [];
  const regionOf = regionResolver(vcd);
  const tabRegion = (tab) => regionOf(tab);
  const fields = vcd.filter(isField);

  // page-rule effect per element (declarative field state)
  const ruleByEl = new Map();
  for (const r of cs.pageBusinessRules || []) {
    const line = humanizeAction(r.action) + (Array.isArray(r.conditions) && r.conditions.length ? " (conditional)" : "");
    ruleByEl.set(r.element, ruleByEl.has(r.element) ? ruleByEl.get(r.element) + "; " + line : line);
  }

  const L = [];
  L.push(`## Design spec — ${entity} (generated)`);
  L.push("");
  L.push("> Generated by `migrate.mjs --spec` from the merged Classic schemas — **present verbatim, do not");
  L.push("> paraphrase**. Layout = structure + contents (one table). Logic = behaviour. ⚠ = confirm before build.");
  L.push("");
  L.push(`- **Entity:** ${entity}${opts.template ? ` · **Template:** ${opts.template}` : ""}${opts.targetPackage ? ` · **Package:** ${opts.targetPackage}` : ""}`);
  L.push(`- **Size:** ${fields.length} fields · ${(cs.details || []).length + (cs.standardFeatures || []).length} details/features · ${(cs.pageBusinessRules || []).length} rules · ${(cs.cardActions || []).length} actions`);
  if (eff.unresolvedParents?.length)
    L.push(`- ⚠ **unresolvedParents:** ${eff.unresolvedParents.join(", ")} — the seed is incomplete; DO NOT build until empty`);
  L.push("");

  // ---- ONE Layout table (structure + contents) ----
  const rows = []; // { region, sort, cells:[element,type,source,rule,additional] }
  for (const f of fields) {
    const col = strip(f.values.control);
    const v = f.values || {};
    const type = esc(v.typeLabel || v.type) + (v.refSchema ? ` (${esc(v.refSchema)})` : "");
    const rule = v.readOnly ? "read-only" : (ruleByEl.get(col) || DASH);
    const tip = v.tip?.content ? `tip: ${esc(v.tip.content)}` : DASH;
    rows.push({ region: regionOf(f.parentName), sort: 0, cells: [esc(dispLabel(f)), type, "PDS." + esc(col), rule, tip] });
  }
  for (const d of cs.details || []) {
    const src = `${esc(d.entity || "?")}${d.dependency ? ` · by ${esc(d.dependency.attributePath)}` : " · ⚠ FK"}`;
    const add = d.columns?.length ? `cols: ${d.columns.map(esc).join(" · ")}` : DASH;
    rows.push({ region: d.tab ? tabRegion(d.tab) : "⚠ unplaced", sort: 1, cells: [esc(d.caption || d.detailSchema || d.entity), "Related list", src, DASH, add] });
  }
  for (const s of cs.standardFeatures || []) {
    const isList = s.uiShape === "list";
    const type = isList ? "Related list" : esc(s.feature);
    const nativeSrc = s.templateProvided ? "template-provided" : "native — confirm component on-stand";
    const src = isList ? `${esc(s.entity || "Activity")} · native` : nativeSrc;
    const add = s.inferredFromEntity ? "⚠ inferred from entity — confirm" : DASH;
    rows.push({ region: s.tab ? tabRegion(s.tab) : "⚠ unplaced", sort: isList ? 1 : 2, cells: [esc(s.feature), type, src, DASH, add] });
  }
  for (const w of cs.widgets || []) {
    rows.push({ region: "Header / top", sort: 2, cells: [esc(w.widget), "Component", w.base ? "template context — provided by the Freedom template" : "native — confirm on-stand", DASH, w.note ? esc(w.note) : DASH] });
  }
  for (const a of cs.cardActions || []) {
    const isProc = /process/i.test(a);
    const isPrint = /print/i.test(a);
    const printAdd = isPrint ? "⚠ only if print reports exist — verify" : DASH;
    const add = isProc ? "⚠ which process — resolve via connected processes on-stand (VwSysProcessEntityConnection); base button names none" : printAdd;
    rows.push({ region: "Card actions", sort: 3, cells: [esc(a.replace(/Button$/, "")), "Action", DASH, DASH, add] });
  }
  // group by region (first-seen order), stable by `sort` then insertion within region
  const order = [];
  const byRegion = new Map();
  rows.forEach((r, i) => { if (!byRegion.has(r.region)) { byRegion.set(r.region, []); order.push(r.region); } byRegion.get(r.region).push({ ...r, i }); });
  // region reading order: the side profile (all islands) FIRST, then tabs, then top widgets, card actions,
  // and finally any flagged/unresolved regions — so profile info is not interleaved with tabs.
  const regionRank = (r) => {
    if (r.startsWith("Side profile") || r === "Header") return 0;
    if (r.startsWith("Tab ")) return 1;
    if (r === "Header / top") return 2;
    if (r === "Card actions") return 3;
    return 4;
  };
  const firstSeen = new Map(order.map((r, i) => [r, i]));
  order.sort((a, b) => regionRank(a) - regionRank(b) || firstSeen.get(a) - firstSeen.get(b));

  // ---- List page (section concerns) comes FIRST — the Main-scope table lists the list page before the
  // form page, so the detailed expansions follow that same order: list page → form page → child pages. ----
  if (section) {
    L.push("### List page");
    const ar = section.addRecordMiniPage;
    const miniPageDesc = ar
      ? `via mini page \`${esc(ar)}\` — migrate it as a Freedom mini page / quick-add`
      : "full edit page (no add-record mini page detected)";
    const addRecordDesc = ar === true
      ? "⚠ via a mini page (name unresolved) — confirm and migrate it as a Freedom mini page / quick-add"
      : miniPageDesc;
    L.push(`- **Add record:** ${addRecordDesc}`);
    L.push(`- **List columns:** ${(section.listColumns || []).length ? section.listColumns.map(esc).join(" · ") : "⚠ not in the schema (profile data) — read the section's saved columns or confirm the list-page columns"}`);
    if ((section.sectionActions || []).length) L.push(`- **Section actions:** ${section.sectionActions.map((a) => `\`${esc(a)}\``).join(" · ")} — migrate as Freedom list-page actions`);
    if (section.processLaunch) L.push(`- **Section process:** ⚠ launches ${(section.processNames || []).join(", ") || "a process"} — wire as a list-page run-process action`);
    L.push("");
  }

  // ---- Form page — its Layout / Logic / Confirm nested under one page heading (the Main-scope form row) ----
  L.push(`### ${entity} form page`);
  L.push("#### Layout");
  L.push("| Region | Element | Type | Source | Rule | Additional |");
  L.push("| --- | --- | --- | --- | --- | --- |");
  for (const region of order) {
    const items = byRegion.get(region).sort((a, b) => a.sort - b.sort || a.i - b.i);
    for (const it of items) L.push(`| ${region} | ${it.cells.join(" | ")} |`);
  }
  L.push("");

  // ---- Logic (behaviour that is not layout): entity filters, handlers, process launch ----
  const logic = [];
  // entity filters — DEDUP by target attribute (a column can carry >1 FILTRATION rule); one row per attr.
  const filtBy = {};
  for (const r of cs.entityBusinessRules || []) {
    filtBy[r.targetAttribute] = filtBy[r.targetAttribute] || [];
    filtBy[r.targetAttribute].push(r);
  }
  for (const [attr, rs] of Object.entries(filtBy)) {
    const unresolved = rs.filter((r) => !r.complete).length;
    const singleEffc = rs[0].complete ? "static filter" : "⚠ dynamic — resolve value";
    const effc = rs.length === 1 ? singleEffc
      : `${rs.length} filters${unresolved ? ` (${unresolved} ⚠ dynamic — resolve value)` : ""}`;
    logic.push([`Filter · ${esc(attr)}`, `${esc(attr)} lookup`, effc, "entity business rule / lookup filter"]);
  }
  // handlers — fold the set<X>Info / clear<X>Info helpers into their on<X>Change trigger row (not separate
  // rows), so the Logic table shows the meaningful behaviours, not every internal helper.
  const stubs = cs.handlerStubs || [];
  const helperBase = (m) => { const mt = /^(?:set|clear)(.+?)Info$/.exec(m); return mt ? mt[1] : null; };
  const triggerBase = (m) => { const mt = /^on(.+?)Chang/.exec(m); return mt ? mt[1] : null; };
  const helpersByBase = {};
  for (const h of stubs) {
    const b = helperBase(h.sourceMethod);
    if (b) { helpersByBase[b] = helpersByBase[b] || []; helpersByBase[b].push(h.sourceMethod); }
  }
  for (const h of stubs) {
    if (helperBase(h.sourceMethod)) continue; // shown folded into its trigger row
    const b = triggerBase(h.sourceMethod);
    const extra = b && helpersByBase[b] ? ` (+ ${helpersByBase[b].join(", ")})` : "";
    logic.push([esc(h.sourceMethod), triggerOf(h.sourceMethod), `imperative (${esc(h.category)})${extra} — review`, "request handler / converter / virtual attr"]);
  }
  if ((cs.needsDecision || []).some((n) => n.kind === "process-launch")) {
    const pn = cs.needsDecision.find((n) => n.kind === "process-launch")?.item;
    logic.push(["Run process", "Run process action", `launch ${esc(pn || "process")}`, pn ? "⚠ verify process name/binding" : "⚠ which process — resolve via connected processes on-stand (VwSysProcessEntityConnection)"]);
  }
  if (logic.length) {
    L.push("#### Logic");
    L.push("| Behaviour | Trigger | Effect | Freedom target |");
    L.push("| --- | --- | --- | --- |");
    for (const row of logic) L.push(`| ${row.join(" | ")} |`);
    L.push("");
  }

  // ---- Confirm before I build (the ⚠ worklist) — the agent appends discovery risks/gaps here ----
  // Only the GENUINE open decisions. Kinds already surfaced in Layout (standard-feature / widget /
  // card-action), in Logic (method / process-launch) or in the Child-pages table (detail-editpage) are
  // NOT re-listed here — that duplication is exactly the noise the plan structure was meant to remove.
  const SHOWN_ELSEWHERE = new Set(["process-launch", "standard-feature", "widget", "card-action", "method", "detail-editpage"]);
  const nd = (cs.needsDecision || []).filter((n) => !SHOWN_ELSEWHERE.has(n.kind));
  if (nd.length) {
    L.push(`#### ⚠ Confirm before I build (${nd.length})`);
    for (const d of nd) L.push(`- **[${esc(d.kind)}]** ${esc(d.item)} — ${strip(d.reason)}`);
    L.push("");
  }

  return L.join("\n");
}

// renderPlan — the WHOLE plan skeleton the agent presents at the gate: an Overview/What-it-does/Pages
// header with `<FILL: …>` placeholders for the few AGENT decisions (scope, environment, package, approach,
// business sentence, template choices) + the GENERATED design spec. Child edit pages are folded into the
// Pages table as `Rebuild (child)` rows (recursive sub-migrations), not a separate section.
// The agent fills the placeholders and pastes VERBATIM — it cannot drop or restructure the generated
// sections (which is what happened when it hand-authored the plan). Corrections go in an Adjustments note.
export function renderPlan(result, opts = {}) {
  const cs = result.changeSet || {};
  const entity = result.entity || "?";
  const fields = (cs.viewConfigDiff || []).filter(isField);
  const childs = result.childPages || [];
  const P = [];
  P.push(`## ${entity} — Classic → Freedom UI`);
  P.push("");
  P.push("### Overview");
  P.push("**Scope:** <FILL: single-section | whole-package> ·");
  P.push("**Environment:** <FILL: environment name> ·");
  P.push("**Package:** <FILL: owning package(s) + lock state → target package>");
  P.push("");
  P.push(`- **Size:** ${fields.length} fields · ${(cs.details || []).length + (cs.standardFeatures || []).length} details/features · ${(cs.pageBusinessRules || []).length} rules · ${(cs.cardActions || []).length} actions`);
  P.push("- **Approach:** <FILL: one sentence — parallel rebuild / reconcile / switch-over; NOT the package/scope>");
  P.push("");
  P.push("### What it does");
  P.push("<FILL: 1–2 sentences, business language — what it is for and who uses it>");
  P.push("");
  // Main scope = the index of the pages this migration covers; each row is expanded below IN THIS ORDER
  // (list page → form page → child pages) under its own `### … page` / `### Child page mappings` section.
  P.push("### Main scope");
  P.push("| Classic | Freedom target | Call |");
  P.push("| --- | --- | --- |");
  P.push("| <FILL: section schema> (list page) | <FILL: Freedom list template> | Rebuild |");
  P.push(`| ${entity} form page | <FILL: Freedom form template> | Rebuild |`);
  // child edit pages belong in Main scope too — each related list's child entity opens its OWN form on
  // add/edit, so it is a page in the migration TREE (a recursive sub-migration), not a side note. The
  // target is a fixed clean value (NOT a free-text FILL — that invited inconsistent status prose); the
  // "does a Freedom form already exist / follow-on" nuance lives in the Child page mappings section below.
  for (const c of childs) P.push(`| ${esc(c.editPage || (c.entity + " form page"))} — opened by detail "${esc(c.via)}"${c.editable === false ? " · view-only" : ""} | Freedom record page | Rebuild (child) |`);
  P.push("");
  if (childs.length) P.push("> **`Rebuild (child)` rows are recursive sub-migrations** — each child page's own mapping is under **Child page mappings** below (generated where the schema was supplied, a `<FILL>` slot otherwise). A related list whose child entity has no Freedom form can't add/edit records.");
  P.push("");
  P.push(renderDesignSpec(result, opts));
  P.push("");
  // Child page mappings — one real design spec per related-list child page (the mapping the listing lacked).
  // Generated inline when the agent supplied the child's schema (childPageSchemas); otherwise a FILL slot
  // that keeps the mapping a REQUIRED, visible deliverable rather than a table row the agent treats as done.
  if (childs.length) {
    P.push("### Child page mappings");
    P.push("");
    for (const c of childs) {
      const head = `${esc(c.entity)} — opened by detail "${esc(c.via)}"${c.editable === false ? " · view-only" : ""}`;
      P.push(`#### Child page: ${head}`);
      if (c.spec) {
        if (c.grandChildren) P.push(`> ${c.grandChildren} nested child page(s) of its own — map those recursively too (step 7).`);
        P.push("");
        P.push(demoteHeadings(c.spec)); // nest the child's ## / ### headings two levels under this ####
      } else if (c.specError) {
        P.push(`> ⚠ child schema supplied but failed to parse: ${esc(c.specError)} — fix the child manifest and re-run.`);
      } else {
        P.push(`> **\`<FILL: recursive sub-migration>\`** — fetch this child's edit page${c.editPage ? ` (\`${esc(c.editPage)}\`)` : " (resolve the schema name via list-pages)"}, run \`migrate.mjs --plan\` on it (or pass it in \`childPageSchemas\`), and paste its generated design spec here. Do NOT leave this as just a row in Pages.`);
      }
      P.push("");
    }
  }
  P.push("> **Fill every `<FILL: …>` above, then present this VERBATIM.** Corrections/enrichments go in an *Adjustments* list at the very end — do NOT edit, reorder, or drop the generated tables/sections (Main scope · List page · form-page Layout/Logic/Confirm · Child page mappings).");
  return P.join("\n");
}
