// ESLint flat config for the repository's first-party ES modules.
//
// Scope is the hand-written .mjs source: the shipped engine and workflow core under skills/, the telemetry
// hooks under hooks/, and the repo scripts under scripts/. Everything else is ignored on purpose:
//   - engine/vendor/** is the pinned third-party parser, guarded by its SHA-256 pin, not by lint;
//   - engine/registry/** is generated by scripts/build-registry-index.mjs, so a finding there is fixed in the
//     generator, which IS linted;
//   - skills/*/*.workflow.js is generated by scripts/build-workflows.mjs from skills/_workflow-core/, which IS
//     linted, so linting the inlined copy would report every finding twice;
//   - engine-tests/**/fixtures/** and engine-tests/**/baseline/** are frozen engine INPUT (legacy ES5 Classic
//     schema bodies and the hand-written scripts the parity runner compares against), never edited;
//   - the remaining .js/.cjs files are CommonJS or host templates outside this config's module setting.
// This file and the packages it loads are contributor tooling only; nothing under skills/ or hooks/ imports them.

import js from "@eslint/js";
import globals from "globals";

export default [
  {
    ignores: [
      "skills/classic-to-freedom-migration/engine/vendor/**",
      "skills/classic-to-freedom-migration/engine/registry/**",
      "skills/*/*.workflow.js",
      "engine-tests/**",
      "tests/**",
      "coverage/**",
      "**/*.js",
      "**/*.cjs",
    ],
  },
  {
    ...js.configs.recommended,
    files: ["skills/**/*.mjs", "scripts/*.mjs", "hooks/**/*.mjs", "eslint.config.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...globals.node },
    },
  },
];
