#!/usr/bin/env python3
"""
Build per-agent context bundles from INDEX.md line ranges.

Usage:
    python3 scripts/build_context_bundle.py [--agent 4] [--out context/.cache/]

Parses context/INDEX.md to extract per-agent file + line-range mappings,
then concatenates the relevant sections into a single markdown bundle.
Eliminates the need for Agent 4 to make 22 separate view() calls.
"""
import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = REPO_ROOT / "context" / "INDEX.md"
CACHE_DIR = REPO_ROOT / "context" / ".cache"

AGENT_READS = {
    1: [
        ("agents/01-environment-setup.md", None),
        ("context/essentials.md", [(230, 277)]),
    ],
    2: [
        ("agents/02-requirements-gathering.md", None),
        ("context/business-checklist.md", None),
    ],
    3: [
        ("agents/03-implementation-plan.md", None),
        ("context/essentials.md", None),
        ("context/schema-reference.md", [(7, 90)]),
        ("context/model-discovery-evidence.md", None),
    ],
    4: [
        ("agents/04-implementation.md", None),
        ("context/ui-reference.md", None),
        ("context/viewconfig-reference.md", None),
        ("context/handlers-reference.md", None),
        ("context/devkit-common-reference.md", None),
        ("context/schema-reference.md", [(7, 29), (64, 111)]),
        ("scripts/mcp_client.py", None),
        ("scripts/page_body_tools.py", None),
    ],
}


def extract_lines(filepath, ranges):
    lines = filepath.read_text(encoding="utf-8").splitlines()
    if ranges is None:
        return lines
    result = []
    for start, end in ranges:
        result.extend(lines[start - 1 : end])
    return result


def build_bundle(agent_num, repo_root=REPO_ROOT):
    reads = AGENT_READS.get(agent_num)
    if not reads:
        print(f"No reads defined for agent {agent_num}", file=sys.stderr)
        return None
    sections = []
    for rel_path, ranges in reads:
        filepath = repo_root / rel_path
        if not filepath.exists():
            sections.append(f"\n<!-- MISSING: {rel_path} -->\n")
            continue
        range_desc = "full" if ranges is None else ", ".join(f"L{s}-{e}" for s, e in ranges)
        sections.append(f"\n<!-- FILE: {rel_path} ({range_desc}) -->\n")
        extracted = extract_lines(filepath, ranges)
        sections.append("\n".join(extracted))
    header = f"# Agent {agent_num} Context Bundle\n\nAuto-generated by `scripts/build_context_bundle.py`.\nDo NOT edit manually — regenerate with `python3 scripts/build_context_bundle.py --agent {agent_num}`.\n"
    return header + "\n".join(sections) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Build per-agent context bundles")
    parser.add_argument("--agent", type=int, choices=[1, 2, 3, 4], help="Build bundle for specific agent (default: all)")
    parser.add_argument("--out", type=str, default=str(CACHE_DIR), help="Output directory")
    args = parser.parse_args()
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    agents = [args.agent] if args.agent else [1, 2, 3, 4]
    for n in agents:
        bundle = build_bundle(n)
        if bundle:
            out_path = out_dir / f"agent-{n}-bundle.md"
            out_path.write_text(bundle, encoding="utf-8")
            line_count = bundle.count("\n")
            print(f"Agent {n}: {out_path} ({line_count} lines)", file=sys.stderr)


if __name__ == "__main__":
    main()
